In [8]:
import numpy as np
from numpy.linalg import eig
from numpy import linalg as LA

Given a transition probability matrix P, we find a steady state vector M.

In [7]:

def find_steady_state(P): #Finds the steady state vector of a Markov chain
  A = P.T
  n=len(P)
  w,v = eig(A)
  w=np.array(w, dtype=np.float32)
  v=np.array(v, dtype=np.float32)
  print(w[0]==1) #First column should be eigenvector associated to 1
  U=np.array(v[:, 0:1]) #extracts first eigenvector
  a=LA.norm(U)
  if U[0] < 0: # sign of entries of eigenvector may need to be flipped
    W=-U
  else: W=U
  c = np.sum(W) #steady state vector should be a probability distribution with sum = 1
  M = (1/c)*W
  return(M)

In [9]:
P = np.array([[.6, .2, .2], [0, .8, .2], [.1, 0, .9]])
A = P.T
M = find_steady_state(P)
print("steady state:\n", M)
print("check:\n", A @ M)

True
steady state:
 [[0.16666667]
 [0.16666667]
 [0.6666667 ]]
check:
 [[0.16666667]
 [0.16666667]
 [0.66666669]]


In [10]:
P = np.array([[0, .5, .5], [1/3, 1/3, 1/3], [.25, .25, .5]])
A = P.T
M = find_steady_state(P)
print("steady state:\n", M)
print("check:\n", A @ M)

True
steady state:
 [[0.22222222]
 [0.3333333 ]
 [0.44444445]]
check:
 [[0.22222222]
 [0.33333333]
 [0.44444444]]


(A^m)*x should approach the steady state as m goes to infinity

In [11]:
def test_convergence(P, epsilon): #Numerically approximates the steady vector by itterating
  A = P.T
  n = len(A)
  x = np.random.rand(n,1) #creats a random vector with entries between 0 and 1
  s = np.sum(x)
  x = (1/s)*x #a distribution should have entries that add to 1
  diff = 1
  while diff > epsilon :
    b = A @ x #b is the new iteration
    diff = LA.norm(b-x)
    x=b #x is fed back into the loop
  M = x
  return(M)


In [13]:
P = np.array([[0, .5, .5], [1/3, 1/3, 1/3], [.25, .25, .5]])
A = P.T
V = test_convergence(P, .00001)
X = A @ V
print("Steady State Approximation:\n", V)
print("Next iteration:\n", X)
print("Euclidean distance:\n", LA.norm(V-X))



Steady State Approximation:
 [[0.22222337]
 [0.33333259]
 [0.44444404]]
Next iteration:
 [[0.22222187]
 [0.33333356]
 [0.44444457]]
Euclidean distance:
 1.8545503428884887e-06


Now compare the numerical solution to the exact solution.


In [14]:
P = np.array([[0, .5, .5], [1/3, 1/3, 1/3], [.25, .25, .5]])
M = find_steady_state(P)
V = test_convergence(P, .00001)
E = abs(V-M)
error = np.sum(E)
print("numerical:\n", V)
print("actual:\n", M)
print("error:\n", error)

True
numerical:
 [[0.22222367]
 [0.3333324 ]
 [0.44444393]]
actual:
 [[0.22222222]
 [0.3333333 ]
 [0.44444445]]
error:
 2.868107101844375e-06


In [17]:
P = np.array([[.6, .2, .2], [0, .8, .2], [.1, 0, .9]])
M = find_steady_state(P)
V = test_convergence(P, .000001)
E = abs(V-M)
error = np.sum(E)
print("numerical:\n", V)
print("actual:\n", M)
print("error:\n", error)

True
numerical:
 [[0.16666573]
 [0.16666855]
 [0.66666572]]
actual:
 [[0.16666667]
 [0.16666667]
 [0.6666667 ]]
error:
 3.7957005878663796e-06
