<a href="https://colab.research.google.com/github/pschwartz222/MA-540-/blob/main/PageRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import eig
from numpy import linalg as LA

In [ ]:
P = np.array([[0, 0, 1/2, 1/3], [0, 0, 0, 1/3], [1/2, 0, 0, 1/3], [1/2, 0, 1/2, 0]])
print(P)

[[0.         0.         0.5        0.33333333]
 [0.         0.         0.         0.33333333]
 [0.5        0.         0.         0.33333333]
 [0.5        0.         0.5        0.        ]]


In [ ]:
def strong_connect(P, d): #input a transition matrix and a parameter d
  n = len(P)
  e=(1-d)/n
  A = np.zeros((n,n)) #The n x n zero matrix
  for i in range(n):
    u = P[:, i:(i+1)]
    if (u[:]==0).all() == True: #check to see if the ith column is the zero vector
      A[:,i]=1/n #if so the entries of A are changed to 1/n
  C = np.full((n,n),e) #every entry of C is e
  hat_P = (d*(A+P))+C #The strongly connect transition matrix
  return(hat_P)



In [ ]:
hat_P = strong_connect(P, .85)
print(hat_P)


[[0.0375     0.25       0.4625     0.32083333]
 [0.0375     0.25       0.0375     0.32083333]
 [0.4625     0.25       0.0375     0.32083333]
 [0.4625     0.25       0.4625     0.0375    ]]


In [ ]:
def approx_steady_state(P, epsilon): #Numerically approximates the steady vector by itterating
  n = len(P)
  x = np.random.rand(n,1) #creats a random vector with entries between 0 and 1
  s = np.sum(x)
  x = (1/s)*x #a distribution should have entries that add to 1
  diff = 1
  while diff > epsilon :
    b = P @ x #b is the new iteration
    diff = LA.norm(b-x)
    x=b #x is fed back into the loop
  M = x
  return(M)

In [ ]:
def find_steady_state(P): #Finds the steady state vector of a Markov chain
  n=len(P)
  w,v = eig(P)
  w=np.array(w, dtype=np.float32)
  v=np.array(v, dtype=np.float32)
  for i in range(n):
    if w[i] == 1: #checks if ith eigenvalue is 1
      U=np.array(v[:,i:(i+1)]) #picks the eigenvalue associated to 1
  if U[0] < 0: # sign of entries of eigenvector may need to be flipped
    W=-U
  else: W=U
  c = np.sum(W) #steady state vector should be a probability distribution with sum = 1
  M = (1/c)*W
  return(M)

In [ ]:
M = find_steady_state(hat_P)
V = approx_steady_state(hat_P, .000001)
E = abs(V-M)
error = np.sum(E)
print("numerical:\n", V)
print("actual:\n", M)
print("error:\n", error)

numerical:
 [[0.27134163]
 [0.15602151]
 [0.27134184]
 [0.30129502]]
actual:
 [[0.27134174]
 [0.15602149]
 [0.27134174]
 [0.301295  ]]
error:
 2.3115713287946704e-07


In [ ]:
P = np.array([[0,1,0,0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
print(P)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [ ]:
hat_P = strong_connect(P, .85)
print(hat_P)

[[0.0375 0.8875 0.0375 0.0375]
 [0.8875 0.0375 0.0375 0.0375]
 [0.0375 0.0375 0.0375 0.8875]
 [0.0375 0.0375 0.8875 0.0375]]


In [ ]:
M = approx_steady_state(hat_P, .000001)
print(M)

[[0.25000012]
 [0.25000013]
 [0.2499996 ]
 [0.25000016]]


In [ ]:
M = find_steady_state(hat_P)
V = approx_steady_state(hat_P, .000001)
E = abs(V-M)
error = np.sum(E)
print("numerical:\n", V)
print("actual:\n", M)
print("error:\n", error)

numerical:
 [[0.24999951]
 [0.25000002]
 [0.25000039]
 [0.25000008]]
actual:
 [[0.25]
 [0.25]
 [0.25]
 [0.25]]
error:
 9.86107943884429e-07
