<a href="https://colab.research.google.com/github/pschwartz222/MA-540-/blob/main/SteadyState1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import eig
from numpy import linalg as LA

In [ ]:

P = np.array([[0, .5, .5], [1/3, 1/3, 1/3], [.25, .25, .5]])
print(P)
print()
A = P.T
print(A)

[[0.         0.5        0.5       ]
 [0.33333333 0.33333333 0.33333333]
 [0.25       0.25       0.5       ]]

[[0.         0.33333333 0.25      ]
 [0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.5       ]]


In [ ]:
w,v=eig(A)
print('Eigenvalues:', w)
print('Eigenvectors:', v)
print()
u=np.array(v, dtype=np.float32)
print(u)

Eigenvalues: [ 1.         -0.30381261  0.13714594]
Eigenvectors: [[-0.37139068 -0.8051731  -0.13550992]
 [-0.55708601  0.51994159 -0.6295454 ]
 [-0.74278135  0.28523152  0.76505532]]

[[-0.37139067 -0.8051731  -0.13550992]
 [-0.557086    0.51994157 -0.6295454 ]
 [-0.74278134  0.28523153  0.7650553 ]]


In [ ]:
V=np.array(v[:,0])
print(V)
print()
U=np.array(u[:,0])
print(U)

[-0.37139068 -0.55708601 -0.74278135]

[-0.37139067 -0.557086   -0.74278134]


In [ ]:
b = A @ U
print("AU=", b)
print("U=", U)

AU= [-0.37139067 -0.557086   -0.74278134]
U= [-0.37139067 -0.557086   -0.74278134]
False


In [ ]:
a= LA.norm(U)
print(a)

1.0


In [ ]:
M=-U
print("M=", M)
print("AM=", A@M)

M= [0.37139067 0.557086   0.74278134]
Norm(M)= 1.0
AM= [0.37139067 0.557086   0.74278134]


In [ ]:
c = np.sum(M)
M = (1/c)*M
print(M)
print(A @ M)

[0.22222222 0.3333333  0.44444445]
